### ISSUE TITLE
1.14.2 crashes at the V3

### ISSUE THREAD

**Issue by LostPandora** [CloudNetService/CloudNet-v3#31]
**Describe the bug**<br>
Server starts easily with the Spigot / PaperMC 1.14.2 but crashes after 5 minutes ca.

Error code:
InvalidTargetException

**Steps for reproducing**<br>

**Expected behavior**<br>
currently none available

**Screenshots**<br>
currently none available

 - System specs: Technical information about your hardware [e.g. CPU = Intel i5 7th Gen etc.]
 - OS: Linux (Debian 9) & Windows 10
 - Version: CloudNet 3 Release 

**Additional context**<br>

currently none available

**Comment by realPanamo** [comment]
``InvalidTargetException`` is not much info. What about the whole stacktrace?

**Comment by realPanamo** [comment]
70921f08198945c78634fbd320913c433cc5a319 might fix this, I had no further issues with spigot 1.14.2 and CloudNet.

**Comment by 4zuree** [comment]
Ah yeah, `InvalidTargetException` is thrown by a reflection based invocation, where the target was a function and this particular function threw an exception during execution. A stacktrace would have been nice though. Due to unsufficient information and low-occurrence of this case, I'd suggest to close this issue and re-open it until further cases with the same exception are known.

**Comment by realPanamo** [comment]
Closing because of the lack of information
