### ISSUE TITLE
cloudperms doesnt work.

### ISSUE THREAD

**Issue by LOGOXX123** [CloudNetService/CloudNet-v3#471]
cloudperms
cloudperms doesnt work

so after you had helped me I wanted to set the ranks / cloudperms user LOGOXX123 add group admin came help to say the command does not give then I tried it via the console perms user LOGOXX123 add group admin then it was successful but I have then did not get wrestled

Steps to reproduce the exception:

i have no recordings my pc is too bad

Expected behavior:

I expected that I would get rank

screenshot:

you don't need a screenshot for something like that, but you can ask me

Environment and used hardware:

my server has 8gm ram ddr4 4 powerful cores 50gb ssd

------ Copy-paste ------
System specifications:
OS:
Version:
--> proxy BUNGEECORD all tasks MINECRAFT_SERVER

Additional context (optional):

I have no further information.

**Comment by fadeoffical** [comment]
Hey,
just because no-one answers you in a span of a few days doesn't mean that no-one will ever answer your github issue. That also won't change by essentially opening and closing the same issue 10 times.
Also, I would recommend you go on the CloudNet discord (I believe you will get there by clicking the banner in the README.md). People there are far more active than on github so your'e far more likely to receive an answer there.

Cheers ^^

**Comment by fadeoffical** [comment]
Another thing: Please keep in mind, that if you use the template, you use it correctly. Stating that you don't want to provide screenshots (or any other information for that matter) because you think that it's unnecessary won't help anyone. Nobody is magic and nobody is going to be able to pin-point the issue just from reading a half-broken sentence.

**Comment by LOGOXX123** [comment]
schau mal den anderen post an habe dir was wichtiges gesagt
