### ISSUE TITLE
Already connected to this network

### ISSUE THREAD

**Issue by Sneakometer** [CloudNetService/CloudNet-v3#514]
**Description of the bug:**
For some reason there is a rare case where the cloud would not register that a player has left the server. If this happens, the player is permanently blocked from the network with the message "you are already connected to this Network" until the entire cloud is shut down and restarted. This message is from the CloudNetBridge module.
I tried kicking the players instance using `players player <name> kick 123` and deleting the player entirely from registry using the  player delete command. This does not help and the player still shows up in `players online`.

It logs the players Login request to the cloud console:
```
[08.07 16:41:13.127] INFO: Login Request from the identity 39f1c949-bd9a-4eca-a1bf-77576616bb44:flunkerer on the proxy Proxy-1
```

However there is no trace of the player in the proxy log, nor the /glist command or on any servers connected with the cloud.

**Steps to reproduce this bug:**

I'm not sure how to reproduce this other than just running the proxy for weeks. This only happened for two players until now, but requires the entire cloud to be restarted in oder to allow them to join again, which is not desirable.

**Expected behavior:**

To properly recognize disconnected players, or at least provide a command to fix it at runtime.

**Screenshots:**

![image](https://user-images.githubusercontent.com/50603525/124943591-eae46c80-e00c-11eb-9389-2e8604de474e.png)
![image](https://user-images.githubusercontent.com/50603525/124943726-0780a480-e00d-11eb-974a-4aed038a61e5.png)
![image](https://user-images.githubusercontent.com/50603525/124943497-d3a57f00-e00c-11eb-9e92-e00a4b3d0db2.png)
![image](https://user-images.githubusercontent.com/50603525/124943797-16675700-e00d-11eb-9743-38bc0ef25957.png)

**Environment and used hardware:**

We are running:
- latest Waterfall 1.17-R0.1-SNAPSHOT:34188b3:443
- CloudNet 3.4.0-SNAPSHOT-2c52ea5
- Java AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)

 System specifications: Ryzen 3000 platform
 OS: Debian
 Version: 10

**Comment by derklaro** [comment]
I can confirm that there are issues with that. We took a look into the code (again) but there is not much we can do now... It's the working of BungeeCord combined with the working of CloudNet which leads to this behaviour. If the issue still occurs, there is now a command option added which allows you to clear the player out of the cache without restarting cloudnet: `pl player <name> kick <reason> --force`. I hope this helps - maybe I will do some further work on this issue in 3.5...

Closing for now as there is not much we can do... I'm sorry for the circumstances this issue is causing.
