### ISSUE TITLE
Service NoSuchFileException with Paper 1.16.5 on latest stable CloudNet Build (Build #11 (10.12.2021, 18:55:47) in branch 3.4/ver/1.18

### ISSUE THREAD

**Issue by EinfachBeez** [CloudNetService/CloudNet-v3#563]
**Description of the bug:**

The bug occurs shortly after starting the cloud. The server is running the latest Paper 1.16.5, with the patch for the Log4J bug included. I noticed that individual services under a template strangely become exceptions. It is surprising that only one service is affected and not the whole template stack.

I have already informed myself on the internet, but I didn't get any real answer, which I almost thought. Maybe the error has already occurred. I'm pretty sure that this problem happened in connection with the Log4j exploit.

**Screenshots:**

https://ibb.co/gFqgfG5

**Environment and used hardware:**
 
 System specifications: 
 OS: Debian 10 Buster under lxc visualization
 Version: CloudNet 3.4

**Comment by derklaro** [comment]
Thanks for the report. First of all, this issue is not related to the log4j2 exploit because CloudNet is not using log4j. It looks like the wrapper is not able to create the file because .wrapper/logs got removed... I cannot reproduce this behaviour at all. Please validate that the directory is there. (You could also delete all files in the directory in the template, as it occurs that there are 16104 log files in there)

**Comment by EinfachBeez** [comment]
I got the problem under control by making a few changes. I'll open the issue again if the same problem occurs.
