### ISSUE TITLE
Template Caching for Remote Storage like SFTP/S3

### ISSUE THREAD

**Issue by Eptiiix** [CloudNetService/CloudNet-v3#899]
### Describe the new feature

There should be a function to cache templates on the nodes for a certain time after download from a SFTP/S3.

### Why do you need this feature?

This would massively limit the traffic consumption and make the servers available faster

### Alternatives

No!

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
Caching templates on a node might result in incorrect results when another node/service (or even the user by hand) updates something in the template. As there is no way to detect changes, other than sending messages to each node in the cluster to invalidate the cache on each taken action (which is really heavy as well) there is no real benefit from caching stuff. If you want faster response times when using S3 you should probably take a look at stuff like CloudFront which will cache your stuff and result in faster loading times as well.

**Comment by Eptiiix** [comment]
Another alternative could be a boolean at each template if it should be cached or not and how long.
In my usage its very important for big files.

And a solution for the incorrect results could be a option to forceUpdate all caches where the boolean is true. (manual per command)

**Comment by derklaro** [comment]
While we could implement this, there are many things we need to consider internally to prevent issues and cache flaws (like for example one call erasing the cache because it's expired while another is copying the data or how we would handle a template update and many more). This means a lot of work for a small feature like this.

Can you maybe explain in more detail which big files you're storing in your templates? I'm quite unsure as I never stumbled upon big files (that it matters) in a normal MC server environment.

**Comment by Eptiiix** [comment]
plugins holding libraries, worlds up to 200mb and a modified paper version.
all these together takes up to 1 minute to prepare the server + 20 seconds for starting the server.

**Comment by 0utplay** [comment]
I see this similar to derklaro, this is a feature for a small target group, which is costly to implement and complex. I wonder why you don't create your own module.

**Comment by Eptiiix** [comment]
I think I dont need the feature anymore as a good alternative got released.
